#!/usr/bin/env python3

import json

with open('../data/schacon.repos.json', 'r') as file:
    data = json.load(file)

data = data[0:5]

with open('chacon.csv', 'w') as chacon_csv:
    for item in data:
        name = item['name']
        html_url = item['html_url']
        updated_at = item['updated_at']
        visibility = item['visibility']

        new_line = name + ',' + html_url + ',' + updated_at + ',' + visibility + '\n'

        chacon_csv.write(new_line)
